# Site wide configuration

title: Alan Andrade
locale: en_US
url: "http://alan-andrade.github.io"


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Alan Andrade
  avatar: bio-photo.jpg
  bio: I was born in Mexico and I'm enjoying thy bay area while living in Oakland \o/. I love the ferry commute and my dream is to make Mexico a better place. My favorite spot is the dock.
  email: alan.andradec+website@gmail.com
  disqus-shortname:
  twitter: _alan_andrade
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: alan-andrade
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: alanandradec
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: alanandrade123
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
